#!/usr/bin/env bash
# Installs HAProxy version 2.4 with the following configurations:



sudo echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

sudo printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 30630-web-01 54.237.93.201:80 check
    server 30630-web-02 100.26.162.209:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

